### ISSUE TITLE
[DATAGRID] columns still not resizing properly

### ISSUE THREAD

**Issue by ariquinones** [ilanddev/ferui#104]
## Datagrid Columns do not resize sometimes

_When going back and forth between using datagrids, sometimes the columns do not extend the full width of the datagrid._

## How To Reproduce

1.  Currently, if you go back and forth between using datagrids and you resize the browser window you will see the columns shrink and not expand back to their original size

![Screen Shot 2020-04-28 at 7 44 20 AM](https://user-images.githubusercontent.com/16388180/80495290-f924fc00-8924-11ea-8e3a-97e62c773ffb.png)

**Comment by JoMas971** [comment]
@ariquinones  What do you mean by 'When going back and forth between using datagrids' exactly ?

**Comment by ariquinones** [comment]
@JoMas971 I recorded how to reproduce. Its within this zip file. You'll see going back and forth between widget screens and playing with the window size is whats making the datagrids act weird.

[Screen Recording 2020-04-30 at 8.44.45 AM.mov.zip](https://github.com/ilanddev/ferui/files/4559027/Screen.Recording.2020-04-30.at.8.44.45.AM.mov.zip)

**Comment by JoMas971** [comment]
Ho i see what's causing the issue... It is dumb... When we resize the window, i'm calling "Resize columns to fit the grid"... So this is a "normal" behaviour because you columns are set to their minimum in order to fit the grid. I'll update this method to take the width of the datagrid into consideration.
Glad we figure this out, thanks !
