### ISSUE TITLE
[UI] Textareas field - Wrong position for the icon (see screenshot)

### ISSUE THREAD

**Issue by mathieupkf** [ilanddev/ferui#19]
<img width="162" alt="Capture d’écran 2019-03-15 à 12 31 16" src="https://user-images.githubusercontent.com/9723290/54454062-3ed13600-471e-11e9-918d-e84c0ff2d122.png">

**Comment by JoMas971** [comment]
Fix by PR #22

**Comment by mathieupkf** [comment]
@JoMas971 - the position is not totally perfect,  please check the design. The color don't looks good as well.

**Comment by JoMas971** [comment]
@mathieupkf well, this icon, as well as the behaviour attach to it, is automatically generated by the browser/OS combo itself. It will not looks the same whether you are on Windows, Linux or Mac OS and it also depends on the browser itself. FYI There is different looks i can have on Mac OS (Firefox and Safari) 

![Screen Shot 2019-03-18 at 20 15 27](https://user-images.githubusercontent.com/3911470/54557231-ecf90c00-49ba-11e9-90f5-89c2e352a149.png)
![Screen Shot 2019-03-18 at 20 15 00](https://user-images.githubusercontent.com/3911470/54557232-ecf90c00-49ba-11e9-9a94-ed4c53a8abbd.png)
 
**I can't change it in any ways...** Maybe one day all browser will agree on this spec and open it to us in order to design it.

The only solution will be to create our own fake "textarea" component and code it from scratch WITHOUT making it use a textarea control, but seriously, it doesn't worth it at all ! That will bring more and more issues again and again and will be much complex to maintain... 

About the position, i'll try my best to fix it.

**Comment by mathieupkf** [comment]
@JoMas971 - Thanks for the explanation. Let's not create a custom one then ;) 
Can you edit the position ? To be closer to the design, you should give it more space. I'll say move it 2px to the left and 2px to the top.

**Comment by JoMas971** [comment]
@mathieupkf yep, that i can do :-)

**Comment by JoMas971** [comment]
@mathieupkf you can check it again :-)
