### ISSUE TITLE
[TREEVIEW] Lets select the initial node without the need to set a timeout.

### ISSUE THREAD

**Issue by JoMas971** [ilanddev/ferui#83]
In current implementation of the treeview, when you initialize the Treeview, you need to use a setTimeout to select the node at initial loads : 

```
setTimeout(() => {
    this.treeView.selectNode(this.treeNodeData); 
});
````

We shouldn't need to use a timeout, instead your `selectNode()` method needs to handle it by itself and select the desired node (without the need to use a setTimeout internally though) once the viewport is loaded with all data (Maybe you can use DomObserver to track the viewport height => when it changes that mean you have loaded your data and you can then select the desired node.)

**IMPORTANT:**  You need to have extra care with server-side loading because the node you're trying to select may not be loaded in the first load of data in the Treeview so you need to load all needed pages until you find the desired node in order to select it.

**Comment by ariquinones** [comment]
Hey Jon, your first statement I think may be misleading. You say the timeout is used to select the node since the node is the one not initialized. But the reason why the timeout was being used is because an *ngIf is being used directly on the tree-view tag so the timeout is to wait for the tree view component itself to be fully available otherwise the `this.treeview` would be undefined. 
If the goal of this issue is to select the first node at initialization, could we not put an Input() boolean property "selectFirst" and if true all we would need to put on the tree view's AfterContentInit lifecycle would be just to select the first node of its node array and all needed would be available at this time

**Comment by JoMas971** [comment]
**Well, we shouldn't need to care about the Treeview being under an `*ngIf` or not, it shouldn't be an issue or a use case anyhow. It should behave correctly no matter what.**

I mean by that, that the node selection should be done through a callback bound to the component itself like we're doing for treeViewConfig and dataRetriever.
We let the developer specify a callback to do whatever he want (selecting the first node or a specific node). We will have more flexibility like that and i don't want to add an extra param like `selectFirst` specially if this option may be a good candidate for being added to the existing treeViewConfig object. (But i'm not sure this is useful though, so let just not add this option yet, we will see if we need to add it later, after using the treeview more often an seeing that this can be useful).

Of course you'll need to create a new interface for this callback, and i think we need to share the treeViewNodes Array + treeviewConfigObject through this callback params, that way the dev doesn't need to create the treeviewNode on his side, he can walk through the nodes that are loaded and select the one that he need to be selected or he can select the first one otherwise. I think we can call this callback `autoSelectNode(nodesArray, treeviewOptions): void`

That way, when the Treeview component loads, it will call this`autoSelectNode` callback (if defined) once the data has been loaded internally, and as a developer, we won't need to bother with a timeout that is not 100% reliable or extra think about having an *ngIf on the component or not...

Also, make sure that if you have a scroll, and select an item internally (at first load for instance) that you actually scroll to the selected item automatically (i don't know if it is already the case). You should follow one of [virtual-scroller methods](https://github.com/rintoj/ngx-virtual-scroller#focus-an-item) to select the item.

**IMPORTANT :** When using the treeview with server-side data retriever, you need to load as many pages as needed internally in order to select the item that the developper is asking for in his callback even if we end up loading all pages/data for nothing if the item he want doesn't exist after all. The dev shouldn't need to do extra work on his side thinking of which page he need to load in order to select the item he want etc...

**Comment by ariquinones** [comment]
Okay thanks Jon! The callback makes a lot of sense. 
I'm not sure why you think on the callback we would need to send the TreeView Config object, seems like its not needed. Instead what I pass in is the select method from the tree view itself so that when the developer sees the list of nodes they select their preferred one and just used the select method right there so no outside work is needed. 
I have my first implementation here: https://github.com/ilanddev/ferui/compare/master...ariquinones:topic/treeview-select-initial-node?expand=1

Works for all tree views (Client side, server side, non root).
Lastly, I'm not sure what you mean about the server-side data retriever loading as many pages as needed. On initialization of the tree view it only ever loads the first level of the nodes from the given TreeNodeData by the developer. At initialization the node array will most likely just be 1 node, in the case of non root maybe more but they're all still within the same level.

**Comment by JoMas971** [comment]
- Yeah ok that make sense for the callback params, all good.

- For server-side treeview though let me explain using an example :  
let say i have a nonRoot treeView with 3 nodes and each ones has 3 layers (they have children, grand-children, grand-grand-children).

```
{
    node1: {
        child1: {
            grand-child1: {
                grand-grand-child1: {...}
                ...
            },
           ...
        },
        child2: {
            grand-child1: {
                grand-grand-child1: {...}
                ...
            },
        },
        child3: {
            grand-child1: {
                grand-grand-child1: {...}
                ...
            },
           ...
        },
       ...
    },
    node2: {
        child1: {
            grand-child1: {
                grand-grand-child1: {...}
                ...
            },
           ...
        },
        child2: {
            grand-child1: {
                grand-grand-child1: {...}
                ...
            },
        },
        child3: {
            grand-child1: {
                grand-grand-child1: {...}
                ...
            },
           ...
        },
       ...
    },
    node3: {
        child1: {
            grand-child1: {
                grand-grand-child1: {...}
                ...
            },
           ...
        },
        child2: {
            grand-child1: {
                grand-grand-child1: {...}
                ...
            },
        },
        child3: {
            grand-child1: {
                grand-grand-child1: {...}
                ...
            },
           ...
        },
       ...
    },
   ...
}
``` 

Let say I select the first grand-child of the third child of the second node in the treeview. Now as a developper i'm storing this node somewhere for some reasons. Then, i go to another page, then reload the Treeview again but i want my previously saved node to be selected by default, how can i do that with current implementation ?

I think we need to add more infos on the TreeNodeData to make it contains the whole hierarchy of parents it may have. (not the whole TreeNodeData objects, but something smaller containing only mandatory infos like what is the parent, then the parent of the parent... etc) So that way, when we rebuild the treeview, if using server-side (even client side actually i'm not sure it's working either on client-side) we would know exactly how many layers we should get at first load. 
We can discuss about that in a call if you want. It can be really tricky to implement indeed.

**Comment by ariquinones** [comment]
Okay Jon, I created the auto selector interface and will only show the first level of the node trees right now for the developer to select.
From what we discussed about opening multiple levels at once and saving the state of the tree view I opened this issue: https://github.com/ilanddev/ferui/issues/86

**Comment by JoMas971** [comment]
This issue has been merged already. I'll close this ticket.
